### Latham.xyz ###

## Join Messages ##

# Message when a player joins the server for the first time
firstJoinMessage: '&a<player> joined for the first time!'

joinMessage: '&a<player> &fhas joined the Server'
quitMessage: '&a<player> &fhas left the Server'